version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    networks:
      - blockchain

  truffle:
    build: .
    depends_on:
      - ganache
    networks:
      - blockchain
    command: tail -f /dev/null  # Mantiene el contenedor en ejecución
networks:
  blockchain:
    driver: bridge
